app = "blackstone"

[build]

[env]

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[experimental]
  auto_rollback = true

[vm]
  size = "shared-cpu-1x"  # Smallest VM
  memory = 256            # Minimum memory

[autoscaling]
  enabled = false